### ISSUE TITLE
'lab_name' and 'exp_name' are incorrect 

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-virtual-power-laboratory-dei#2]
'lab_name' and 'exp_name' are incorrect 
References: 
Lab URL: [http://vp-dei.vlabs.ac.in](http://vp-dei.vlabs.ac.in)
Lab Id: ee06
Lab Name: Virtual Power Lab

**Comment by mrudhvika940** [comment]
Special characters in exp_name were removed and also updated with the respective experiment name and lab name.

**Comment by sravanthimodepu** [comment]
Able to get the analytics usage. Hence closing the issue.
